$axure.loadCurrentPage({
  "url":"team.html",
  "generationDate":new Date(1387558153617.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d145f46fb9d849f78979e055f6223a5a",
    "type":"Axure:Page",
    "name":"Team",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFF4F4F4},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
},
      "b":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6cd6d450d7ab4dcea4f2b960fe29fd33",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":51},
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
}},
          "objects":[{
              "id":"b29a88e2801a4976a10eda363bb0d4f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":51},
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/benefits/u6.png"}},
{
          "id":"439092bdba514d258a91a3a306429a86",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Yanone Kaffeesatz ExtraLight', 'Yanone Kaffeesatz'",
            "fontSize":"48px",
            "fontWeight":"200",
            "location":{
              "x":118,
              "y":44},
            "size":{
              "width":292,
              "height":54}},
          "adaptiveStyles":{
            "a":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF64E050,
                "opacity":1}},
            "b":{
}},
          "objects":[{
              "id":"d1347e541cec49ad91c4d51c117c0a2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Yanone Kaffeesatz ExtraLight', 'Yanone Kaffeesatz'",
                "fontSize":"48px",
                "fontWeight":"200",
                "location":{
                  "x":118,
                  "y":44},
                "size":{
                  "width":292,
                  "height":54}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"e3b9d03d0c364515b62f63200b6d1340",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":456,
              "y":584},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"32px",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":456,
                "y":660},
              "size":{
                "width":336,
                "height":50},
              "limbo":false,
              "borderWidth":"-1"},
            "b":{
              "fontSize":"28px",
              "location":{
                "x":318,
                "y":460},
              "size":{
                "width":225,
                "height":50}}},
          "objects":[{
              "id":"7dd33467767c47ba816e2787fc3a0b48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":456,
                  "y":584},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"acb282597838414ea0aa71ed880e78c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":456,
              "y":627},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":456,
                "y":703},
              "size":{
                "width":336,
                "height":50},
              "limbo":false,
              "borderWidth":"-1"},
            "b":{
              "fontSize":"20px",
              "location":{
                "x":318,
                "y":503},
              "size":{
                "width":225,
                "height":50}}},
          "objects":[{
              "id":"7659ff58e9d54aeaa529ddeea1b7bad2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":456,
                  "y":627},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"ab832d820fbf41588f01370c6623703d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":456,
              "y":664},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontName":"",
              "fontSize":"28px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":456,
                "y":740},
              "size":{
                "width":336,
                "height":50},
              "limbo":false,
              "borderWidth":"-1"},
            "b":{
              "fontSize":"20px",
              "location":{
                "x":318,
                "y":540},
              "size":{
                "width":225,
                "height":50}}},
          "objects":[{
              "id":"aaa9b8a2b20d44709b3131d64ed83d6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":456,
                  "y":664},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"45866846c0194b3ca4df09235479111a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":584},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"32px",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":120,
                "y":660},
              "size":{
                "width":336,
                "height":50},
              "limbo":false,
              "borderWidth":"-1"},
            "b":{
              "fontSize":"28px",
              "location":{
                "x":120,
                "y":460},
              "size":{
                "width":225,
                "height":50}}},
          "objects":[{
              "id":"1bc32b6c1fd849dab428702c1a335009",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":584},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"01b78948893b45b4b73343fedea40df3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":627},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":120,
                "y":703},
              "size":{
                "width":336,
                "height":50},
              "limbo":false,
              "borderWidth":"-1"},
            "b":{
              "fontSize":"20px",
              "location":{
                "x":120,
                "y":503},
              "size":{
                "width":225,
                "height":50}}},
          "objects":[{
              "id":"d1ae9aa0ff734edeace73421438730b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":627},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"9c9086cd24734f5da497fd998371572a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":664},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontName":"",
              "fontSize":"28px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":120,
                "y":740},
              "size":{
                "width":336,
                "height":50},
              "limbo":false,
              "borderWidth":"-1"},
            "b":{
              "fontSize":"20px",
              "location":{
                "x":120,
                "y":540},
              "size":{
                "width":225,
                "height":50}}},
          "objects":[{
              "id":"369db05d22c34a178442cdab83c48f9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":664},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"f997c68514f94d90a9528d1786ea5f65",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":792,
              "y":584},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"32px",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":792,
                "y":660},
              "size":{
                "width":336,
                "height":50},
              "limbo":false,
              "borderWidth":"-1"},
            "b":{
              "fontSize":"28px",
              "location":{
                "x":517,
                "y":460},
              "size":{
                "width":225,
                "height":50}}},
          "objects":[{
              "id":"3d46314e3c184a7688b0f1e6b7999df9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":792,
                  "y":584},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"69f0e3de208a449b903c9c315b653c08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":792,
              "y":627},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":792,
                "y":703},
              "size":{
                "width":336,
                "height":50},
              "limbo":false,
              "borderWidth":"-1"},
            "b":{
              "fontSize":"20px",
              "location":{
                "x":517,
                "y":503},
              "size":{
                "width":225,
                "height":50}}},
          "objects":[{
              "id":"e29f05eb578f4371b3ee057c63093b06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":792,
                  "y":627},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"49b8fc0564274218973b5117fb973286",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":792,
              "y":664},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontName":"",
              "fontSize":"28px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":792,
                "y":740},
              "size":{
                "width":336,
                "height":50},
              "limbo":false,
              "borderWidth":"-1"},
            "b":{
              "fontSize":"20px",
              "location":{
                "x":517,
                "y":540},
              "size":{
                "width":225,
                "height":50}}},
          "objects":[{
              "id":"e3ec14c8a3c14b8787bfa58d8ffa8a94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":792,
                  "y":664},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"1394d062b0ac4a448415c9afa379f870",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1128,
              "y":584},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"32px",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":1128,
                "y":660},
              "size":{
                "width":336,
                "height":50},
              "limbo":false,
              "borderWidth":"-1"},
            "b":{
              "fontSize":"28px",
              "location":{
                "x":715,
                "y":460},
              "size":{
                "width":225,
                "height":50}}},
          "objects":[{
              "id":"bec605be3bf24b2ab10bc27913aeeab4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1128,
                  "y":584},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"bb8d91103f2b4f8a9738a3cc5c1f1dcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1128,
              "y":627},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":1128,
                "y":703},
              "size":{
                "width":336,
                "height":50},
              "limbo":false,
              "borderWidth":"-1"},
            "b":{
              "fontSize":"20px",
              "location":{
                "x":715,
                "y":503},
              "size":{
                "width":225,
                "height":50}}},
          "objects":[{
              "id":"a0c9276c4f844c4ebcdb9eac3736999b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1128,
                  "y":627},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"c31c18e9534c477fb138f733fef19939",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1128,
              "y":664},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontName":"",
              "fontSize":"28px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":1128,
                "y":740},
              "size":{
                "width":336,
                "height":50},
              "limbo":false,
              "borderWidth":"-1"},
            "b":{
              "fontSize":"20px",
              "location":{
                "x":715,
                "y":540},
              "size":{
                "width":225,
                "height":50}}},
          "objects":[{
              "id":"0f4326fb9fbe455abe755da1b341f4a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1128,
                  "y":664},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"2762da2d49094ec29bb155c40bdf6db1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "location":{
              "x":1464,
              "y":584},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":1464,
                "y":660},
              "size":{
                "width":336,
                "height":50},
              "limbo":false,
              "borderWidth":"-1"},
            "b":{
              "size":{
                "width":225,
                "height":50},
              "limbo":true}},
          "objects":[{
              "id":"e042c91f01c44b2499d28c0750dcb497",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "location":{
                  "x":1464,
                  "y":584},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"d86f8f065f1f4b0aaed6bc497792790a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF39AA27,
              "opacity":1},
            "location":{
              "x":1464,
              "y":627},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":1464,
                "y":703},
              "size":{
                "width":336,
                "height":50},
              "limbo":false,
              "borderWidth":"-1"},
            "b":{
              "location":{
                "x":950,
                "y":460},
              "size":{
                "width":225,
                "height":50}}},
          "objects":[{
              "id":"2072d776997641358d651ef46be039ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF39AA27,
                  "opacity":1},
                "location":{
                  "x":1464,
                  "y":627},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"437d36edefbe4c8a97cd610ce8bcc783",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":664},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontName":"",
              "fontSize":"28px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":1464,
                "y":740},
              "size":{
                "width":336,
                "height":50},
              "limbo":false,
              "borderWidth":"-1"},
            "b":{
              "size":{
                "width":225,
                "height":50},
              "limbo":true}},
          "objects":[{
              "id":"6fc61efbf0c14ed29ea6d8b9a4af10d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1464,
                  "y":664},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"1247c2ec385d489cbb2e1c80d7d8397f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":170},
            "size":{
              "width":1681,
              "height":404}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":120,
                "y":246}},
            "b":{
              "location":{
                "x":120,
                "y":199},
              "size":{
                "width":1126,
                "height":271}}},
          "objects":[{
              "id":"638e765bf119477d8c276b4155949c89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":170},
                "size":{
                  "width":1681,
                  "height":404}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/team/u34.png",
            "normal~a":"images/team/u34.png",
            "normal~b":"images/team/u34.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6cd6d450d7ab4dcea4f2b960fe29fd33":{
      "scriptId":"u0"},
    "b29a88e2801a4976a10eda363bb0d4f9":{
      "scriptId":"u1"},
    "439092bdba514d258a91a3a306429a86":{
      "scriptId":"u2"},
    "d1347e541cec49ad91c4d51c117c0a2e":{
      "scriptId":"u3"},
    "e3b9d03d0c364515b62f63200b6d1340":{
      "scriptId":"u4"},
    "7dd33467767c47ba816e2787fc3a0b48":{
      "scriptId":"u5"},
    "acb282597838414ea0aa71ed880e78c7":{
      "scriptId":"u6"},
    "7659ff58e9d54aeaa529ddeea1b7bad2":{
      "scriptId":"u7"},
    "ab832d820fbf41588f01370c6623703d":{
      "scriptId":"u8"},
    "aaa9b8a2b20d44709b3131d64ed83d6d":{
      "scriptId":"u9"},
    "45866846c0194b3ca4df09235479111a":{
      "scriptId":"u10"},
    "1bc32b6c1fd849dab428702c1a335009":{
      "scriptId":"u11"},
    "01b78948893b45b4b73343fedea40df3":{
      "scriptId":"u12"},
    "d1ae9aa0ff734edeace73421438730b0":{
      "scriptId":"u13"},
    "9c9086cd24734f5da497fd998371572a":{
      "scriptId":"u14"},
    "369db05d22c34a178442cdab83c48f9c":{
      "scriptId":"u15"},
    "f997c68514f94d90a9528d1786ea5f65":{
      "scriptId":"u16"},
    "3d46314e3c184a7688b0f1e6b7999df9":{
      "scriptId":"u17"},
    "69f0e3de208a449b903c9c315b653c08":{
      "scriptId":"u18"},
    "e29f05eb578f4371b3ee057c63093b06":{
      "scriptId":"u19"},
    "49b8fc0564274218973b5117fb973286":{
      "scriptId":"u20"},
    "e3ec14c8a3c14b8787bfa58d8ffa8a94":{
      "scriptId":"u21"},
    "1394d062b0ac4a448415c9afa379f870":{
      "scriptId":"u22"},
    "bec605be3bf24b2ab10bc27913aeeab4":{
      "scriptId":"u23"},
    "bb8d91103f2b4f8a9738a3cc5c1f1dcc":{
      "scriptId":"u24"},
    "a0c9276c4f844c4ebcdb9eac3736999b":{
      "scriptId":"u25"},
    "c31c18e9534c477fb138f733fef19939":{
      "scriptId":"u26"},
    "0f4326fb9fbe455abe755da1b341f4a3":{
      "scriptId":"u27"},
    "2762da2d49094ec29bb155c40bdf6db1":{
      "scriptId":"u28"},
    "e042c91f01c44b2499d28c0750dcb497":{
      "scriptId":"u29"},
    "d86f8f065f1f4b0aaed6bc497792790a":{
      "scriptId":"u30"},
    "2072d776997641358d651ef46be039ca":{
      "scriptId":"u31"},
    "437d36edefbe4c8a97cd610ce8bcc783":{
      "scriptId":"u32"},
    "6fc61efbf0c14ed29ea6d8b9a4af10d9":{
      "scriptId":"u33"},
    "1247c2ec385d489cbb2e1c80d7d8397f":{
      "scriptId":"u34"},
    "638e765bf119477d8c276b4155949c89":{
      "scriptId":"u35"}}});