$axure.loadCurrentPage({
  "url":"benefits.html",
  "generationDate":new Date(1387558153345.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"549d64384c5245b9b70449b298fc49af",
    "type":"Axure:Page",
    "name":"Benefits",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFF4F4F4},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
},
      "b":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ba47e25049374711ad0ae985339270f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":479},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fill":{
                "fillType":"solid",
                "color":0xFF64E050},
              "location":{
                "x":910,
                "y":757},
              "size":{
                "width":233,
                "height":233},
              "limbo":false,
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"116"},
            "b":{
              "location":{
                "x":710,
                "y":528},
              "size":{
                "width":140,
                "height":140}}},
          "objects":[{
              "id":"c1450a7bde654747aa62e71398aa4df7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":479},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"images/benefits/u0_a.png",
            "normal~b":"images/benefits/u0_b.png"}},
{
          "id":"47fd1b95522748738f116739d1c4bf63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":193},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fill":{
                "fillType":"solid",
                "color":0xFF64E050},
              "location":{
                "x":910,
                "y":469},
              "size":{
                "width":233,
                "height":233},
              "limbo":false,
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"116"},
            "b":{
              "location":{
                "x":710,
                "y":355},
              "size":{
                "width":140,
                "height":140}}},
          "objects":[{
              "id":"b0fc7168bfff4583af582503f2ed0309",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":193},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"images/benefits/u0_a.png",
            "normal~b":"images/benefits/u0_b.png"}},
{
          "id":"9788af9a0a7d4065a53bb54240db631f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":910,
              "y":183},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fill":{
                "fillType":"solid",
                "color":0xFF64E050},
              "size":{
                "width":233,
                "height":233},
              "limbo":false,
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"116"},
            "b":{
              "location":{
                "x":710,
                "y":183},
              "size":{
                "width":140,
                "height":140}}},
          "objects":[{
              "id":"4151edec0da84bfd852ca351a9e4155a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":910,
                  "y":183},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"images/benefits/u0_a.png",
            "normal~b":"images/benefits/u0_b.png"}},
{
          "id":"f6e5b68279264a4bb946907179937828",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":51},
            "size":{
              "width":41,
              "height":41},
            "limbo":true,
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
            "a":{
              "limbo":false},
            "b":{
}},
          "objects":[{
              "id":"fd7eaa7e53b54951bea7a1540fdbb7e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":51},
                "size":{
                  "width":41,
                  "height":41},
                "limbo":true,
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/benefits/u6.png",
            "normal~a":"images/benefits/u6.png",
            "normal~b":"images/benefits/u6.png"}},
{
          "id":"94a42e44342e4e35aa1ba321cf8bfe35",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Yanone Kaffeesatz ExtraLight', 'Yanone Kaffeesatz'",
            "fontSize":"48px",
            "fontWeight":"200",
            "location":{
              "x":118,
              "y":44},
            "size":{
              "width":154,
              "height":54},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF64E050,
                "opacity":1},
              "limbo":false},
            "b":{
}},
          "objects":[{
              "id":"a2702702b5fc4ebc87a48a6583b85b7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Yanone Kaffeesatz ExtraLight', 'Yanone Kaffeesatz'",
                "fontSize":"48px",
                "fontWeight":"200",
                "location":{
                  "x":118,
                  "y":44},
                "size":{
                  "width":154,
                  "height":54},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"b34ff869206d4e1492a4bdaa7e18f92a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Yanone Kaffeesatz ExtraLight', 'Yanone Kaffeesatz'",
            "fontSize":"24px",
            "fontWeight":"200",
            "lineSpacing":"38px",
            "location":{
              "x":120,
              "y":500},
            "size":{
              "width":540,
              "height":168},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"36px",
              "lineSpacing":"52px",
              "location":{
                "x":120,
                "y":701},
              "size":{
                "width":710,
                "height":289},
              "limbo":false},
            "b":{
              "fontSize":"28px",
              "lineSpacing":"36px",
              "location":{
                "x":120,
                "y":469},
              "size":{
                "width":520,
                "height":199}}},
          "objects":[{
              "id":"5347340f8b5e4f2792dbec74fc6f4095",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Yanone Kaffeesatz ExtraLight', 'Yanone Kaffeesatz'",
                "fontSize":"24px",
                "fontWeight":"200",
                "lineSpacing":"38px",
                "location":{
                  "x":120,
                  "y":500},
                "size":{
                  "width":540,
                  "height":168},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"7831c784fc2144a997ef24f73794055f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Yanone Kaffeesatz ExtraLight', 'Yanone Kaffeesatz'",
            "fontSize":"36px",
            "fontWeight":"200",
            "verticalAlignment":"middle",
            "location":{
              "x":874,
              "y":183},
            "size":{
              "width":372,
              "height":140},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"72px",
              "location":{
                "x":1181,
                "y":183},
              "size":{
                "width":619,
                "height":233},
              "limbo":false},
            "b":{
              "fontSize":"36px",
              "location":{
                "x":874,
                "y":183},
              "size":{
                "width":372,
                "height":140}}},
          "objects":[{
              "id":"e00ba84df7484b77acfc18cbdb714ac4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Yanone Kaffeesatz ExtraLight', 'Yanone Kaffeesatz'",
                "fontSize":"36px",
                "fontWeight":"200",
                "verticalAlignment":"middle",
                "location":{
                  "x":874,
                  "y":183},
                "size":{
                  "width":372,
                  "height":140},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"77c9a91966864fa4b24350155d31ccff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Yanone Kaffeesatz ExtraLight', 'Yanone Kaffeesatz'",
            "fontSize":"36px",
            "fontWeight":"200",
            "verticalAlignment":"middle",
            "location":{
              "x":874,
              "y":355},
            "size":{
              "width":372,
              "height":140},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"72px",
              "location":{
                "x":1181,
                "y":470},
              "size":{
                "width":619,
                "height":233},
              "limbo":false},
            "b":{
              "fontSize":"36px",
              "location":{
                "x":874,
                "y":355},
              "size":{
                "width":372,
                "height":140}}},
          "objects":[{
              "id":"80b347586c74446dbcb5c8457aa9f4ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Yanone Kaffeesatz ExtraLight', 'Yanone Kaffeesatz'",
                "fontSize":"36px",
                "fontWeight":"200",
                "verticalAlignment":"middle",
                "location":{
                  "x":874,
                  "y":355},
                "size":{
                  "width":372,
                  "height":140},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"11663ab0e1da45f9bec6578fb24448b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Yanone Kaffeesatz ExtraLight', 'Yanone Kaffeesatz'",
            "fontSize":"36px",
            "fontWeight":"200",
            "verticalAlignment":"middle",
            "location":{
              "x":874,
              "y":528},
            "size":{
              "width":371,
              "height":140},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"72px",
              "location":{
                "x":1181,
                "y":757},
              "size":{
                "width":618,
                "height":233},
              "limbo":false},
            "b":{
              "fontSize":"36px",
              "location":{
                "x":874,
                "y":528},
              "size":{
                "width":371,
                "height":140}}},
          "objects":[{
              "id":"8aceb723f0624a2a9cbbaec4f9c82663",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Yanone Kaffeesatz ExtraLight', 'Yanone Kaffeesatz'",
                "fontSize":"36px",
                "fontWeight":"200",
                "verticalAlignment":"middle",
                "location":{
                  "x":874,
                  "y":528},
                "size":{
                  "width":371,
                  "height":140},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"f98051e30219462eae8506a3d737a062",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":183},
            "size":{
              "width":426,
              "height":290},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":710,
                "height":483},
              "limbo":false},
            "b":{
              "size":{
                "width":530,
                "height":265}}},
          "objects":[{
              "id":"a51a3c347f254e078c1ec3bdcc96bb4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":183},
                "size":{
                  "width":426,
                  "height":290},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/benefits/u18.png",
            "normal~a":"images/benefits/u18_a.png",
            "normal~b":"images/benefits/u18_b.png"}},
{
          "id":"b4a3133f9e8548059b5bc881433790d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Yanone Kaffeesatz'",
            "fontSize":"36px",
            "location":{
              "x":120,
              "y":130},
            "size":{
              "width":560,
              "height":60},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false},
            "b":{
}},
          "objects":[{
              "id":"fdb10778ef1c490da93ad02eec2f6fbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Yanone Kaffeesatz'",
                "fontSize":"36px",
                "location":{
                  "x":120,
                  "y":130},
                "size":{
                  "width":560,
                  "height":60},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ba47e25049374711ad0ae985339270f7":{
      "scriptId":"u0"},
    "c1450a7bde654747aa62e71398aa4df7":{
      "scriptId":"u1"},
    "47fd1b95522748738f116739d1c4bf63":{
      "scriptId":"u2"},
    "b0fc7168bfff4583af582503f2ed0309":{
      "scriptId":"u3"},
    "9788af9a0a7d4065a53bb54240db631f":{
      "scriptId":"u4"},
    "4151edec0da84bfd852ca351a9e4155a":{
      "scriptId":"u5"},
    "f6e5b68279264a4bb946907179937828":{
      "scriptId":"u6"},
    "fd7eaa7e53b54951bea7a1540fdbb7e4":{
      "scriptId":"u7"},
    "94a42e44342e4e35aa1ba321cf8bfe35":{
      "scriptId":"u8"},
    "a2702702b5fc4ebc87a48a6583b85b7c":{
      "scriptId":"u9"},
    "b34ff869206d4e1492a4bdaa7e18f92a":{
      "scriptId":"u10"},
    "5347340f8b5e4f2792dbec74fc6f4095":{
      "scriptId":"u11"},
    "7831c784fc2144a997ef24f73794055f":{
      "scriptId":"u12"},
    "e00ba84df7484b77acfc18cbdb714ac4":{
      "scriptId":"u13"},
    "77c9a91966864fa4b24350155d31ccff":{
      "scriptId":"u14"},
    "80b347586c74446dbcb5c8457aa9f4ac":{
      "scriptId":"u15"},
    "11663ab0e1da45f9bec6578fb24448b7":{
      "scriptId":"u16"},
    "8aceb723f0624a2a9cbbaec4f9c82663":{
      "scriptId":"u17"},
    "f98051e30219462eae8506a3d737a062":{
      "scriptId":"u18"},
    "a51a3c347f254e078c1ec3bdcc96bb4e":{
      "scriptId":"u19"},
    "b4a3133f9e8548059b5bc881433790d0":{
      "scriptId":"u20"},
    "fdb10778ef1c490da93ad02eec2f6fbc":{
      "scriptId":"u21"}}});